In [1]:
pwd

'C:\\Users\\amao'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
np.__version__
#https://www.runoob.com/  上面有numpy的细节教程 其他都在PythonII收藏夹里面

'1.16.5'

In [4]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
# nested lists result in multi-dimensional arrays
#The inner lists are treated as rows of the resulting two-dimensional array.
b=np.array([range(i, i + 3) for i in [2, 4, 6]])

In [9]:
print(b)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [10]:
b.dtype

dtype('int32')

In [11]:
b.ndim

2

In [12]:
b.shape

(3, 3)

In [14]:
b.size

9

In [21]:
b.itemsize

4

In [22]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Create a 3x5 floating-point array filled with ones 3行5列
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function) #not including 20 as well
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.69152782, 0.5319609 , 0.80370319],
       [0.3620598 , 0.11465452, 0.76448392],
       [0.49469147, 0.8207325 , 0.3638524 ]])

In [28]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
Testnp = np.random.normal(0, 1, (5,5)) #数组越小 偏差越大 不论是平均值还是标准偏差 数组大了后就会好转 平均值趋近0 标准偏差趋近1
print(Testnp)

[[-0.25891399  0.62919272  0.40594815  1.12274764 -0.36804269]
 [-0.86302459 -0.85398697  0.66039473  0.17551479  1.50230176]
 [-0.64251887  1.65416577 -0.91776127  0.18022212 -1.33704962]
 [ 0.24429733 -0.8524665  -0.55088101  0.74431919  0.71288754]
 [-0.24325703  0.77430452 -1.44554794 -0.26291195  1.01455062]]


In [29]:
np.average(Testnp)

0.0489793778072767

In [30]:
np.std(Testnp)

0.8478702184701785

In [35]:
# Create a 3x3 array of random integers in the interval [0, 10) 特别注意包括0 但不包括10
np.random.randint(0, 10, (3, 3))

array([[4, 1, 1],
       [5, 4, 7],
       [6, 2, 4]])

In [36]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [38]:
"""
Data type	Description
bool_	Boolean (True or False) stored as a byte
int_	Default integer type (same as C long; normally either int64 or int32)
intc	Identical to C int (normally int32 or int64)
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8	Byte (-128 to 127)
int16	Integer (-32768 to 32767)
int32	Integer (-2147483648 to 2147483647)
int64	Integer (-9223372036854775808 to 9223372036854775807)
uint8	Unsigned integer (0 to 255)
uint16	Unsigned integer (0 to 65535)
uint32	Unsigned integer (0 to 4294967295)
uint64	Unsigned integer (0 to 18446744073709551615)
float_	Shorthand for float64.
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_	Shorthand for complex128.
complex64	Complex number, represented by two 32-bit floats
complex128	Complex number, represented by two 64-bit floats

"""

np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [39]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [40]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [42]:
print(x3[0,0,0])

8


In [44]:
print(x3[1,0,0])

0


In [45]:
print(x3[2,0,0])

4


In [46]:
print("x3 ndim: ", x3.ndim) #number of dimensions
print("x3 shape:", x3.shape)#the size of each dimension
print("x3 size: ", x3.size)#the total size of the array
print("dtype:", x3.dtype) #data type

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32


In [47]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [48]:
print(x1)

[5 0 3 3 7 9]


In [49]:
x1[0]

5

In [50]:
x1[-1]

9

In [51]:
x1[len(x1)-1]

9

In [52]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [53]:
x2[0,0]

3

In [54]:
x2[0,-1]

4

In [55]:
x2[0, 0] = 26
print(x2)

[[26  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [56]:
x1[0] = 3.14159  # this will be truncated!
print(x1)

[3 0 3 3 7 9]


In [57]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
x[:5]  # first five elements x[:5]=x[0:4]=x[0]x[1]x[2]x[3]x[4x[1::2]  # every other element, starting at index 1]

array([0, 1, 2, 3, 4])

In [59]:
x[5:]  # elements after index 5 x[5:]=x[5:len-1]

array([5, 6, 7, 8, 9])

In [60]:
x[4:7]  # middle sub-array #not including right boundary

array([4, 5, 6])

In [61]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [62]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [63]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [65]:
x2

array([[26,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [66]:
x2[:2, :3]  # two rows, three columns

array([[26,  5,  2],
       [ 7,  6,  8]])

In [67]:
x2[:3, ::2]  # all rows, every other column

array([[26,  2],
       [ 7,  8],
       [ 1,  7]])

In [68]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 26]])

In [69]:
print(x2[:, 0])  # first column of x2

[26  7  1]


In [70]:
print(x2[0, :])  # first row of x2

[26  5  2  4]


In [71]:
print(x2[0])  # equivalent to x2[0, :]

[26  5  2  4]


In [72]:
print(x2)

[[26  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [73]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[26  5]
 [ 7  6]]


In [74]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [75]:
print(x2) #change in x2_sub will also be reflected in x2
#x2_sub的改变也会导致x2的改变 说明x2_sub是直接引用x2的源数据 或者说是x2的部分引用

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [76]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [77]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [78]:
print(x2) #利用copy可以解决这个问题

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [79]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [81]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [82]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [83]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [84]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis 也就是行增加 列不变
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [85]:
# concatenate along the second axis (zero-indexed) #列增加 行不变
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [87]:
# concatenate along the first axis 也就是行增加 列不变
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [88]:
#For working with arrays of mixed dimensions
#it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid]) #行增加 列不变 vstack相当于水平堆叠 也就是增加行数

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [89]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y]) #行不变 列增加 hstack相当于垂直堆叠 也就是增加列数

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [90]:
#对于3D数据 Similary, np.dstack will stack arrays along the third axis.
z = np.array(range(1,9)).reshape(2,2,2) # 2 2 2 is for z x y
print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [92]:
zadd = np.array(range(9,13)).reshape(2,2,1) # 2 in z 2 in x 1 in y
print(zadd)

[[[ 9]
  [10]]

 [[11]
  [12]]]


In [93]:
np.dstack([zadd,z])

array([[[ 9,  1,  2],
        [10,  3,  4]],

       [[11,  5,  6],
        [12,  7,  8]]])

In [95]:
np.dstack([z,zadd])  # 2 2 2 change to 2 2 3 the third axis + 1

array([[[ 1,  2,  9],
        [ 3,  4, 10]],

       [[ 5,  6, 11],
        [ 7,  8, 12]]])

In [96]:
zadd = np.array(range(9,13)).reshape(2,2,1)
z3 = np.dstack([z,zadd])
print(z3.shape)

(2, 2, 3)


In [97]:
np.concatenate([z,z], axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [98]:
print(zadd.shape)
print(z.shape)

(2, 2, 1)
(2, 2, 2)


In [113]:
np.concatenate([z,zadd], axis=2) #axis=012 is z x y

array([[[ 1,  2,  9],
        [ 3,  4, 10]],

       [[ 5,  6, 11],
        [ 7,  8, 12]]])

In [100]:
zadd1 = np.array(range(9,13)).reshape(1,2,2)
print(zadd1)

[[[ 9 10]
  [11 12]]]


In [102]:
np.concatenate([z,zadd1], axis=0) #axis=012 is z x y

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [103]:
np.concatenate([zadd1,z], axis=0) #axis=012 is z x y

array([[[ 9, 10],
        [11, 12]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])

In [104]:
zadd2 = np.array(range(9,13)).reshape(2,1,2)
print(zadd2)

[[[ 9 10]]

 [[11 12]]]


In [105]:
np.concatenate([z,zadd2], axis=1) #axis=012 is z x y

array([[[ 1,  2],
        [ 3,  4],
        [ 9, 10]],

       [[ 5,  6],
        [ 7,  8],
        [11, 12]]])

In [106]:
#splitting
x = [1, 2, 3, 4,5, 6, 7, 8,9,10]
x1, x2, x3 = np.split(x, [4, 7]) # 4 and 7这里是索引 并且不属于划分出来的subarray 或者你可以认为划分出来不包含索引所指的项
print(x1, x2, x3)

[1 2 3 4] [5 6 7] [ 8  9 10]


In [107]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
upper, lower = np.vsplit(grid, [2]) #默认是沿着axis=0分隔 因为2D数据 所以axis=0对应行 [2]说明第三行划分 因为第三行不包含在subarray里面 
#所以刚好是2行 2行 或者简单理解为沿着x轴切 水平切
print(upper)
print('--------------')
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
--------------
[[ 8  9 10 11]
 [12 13 14 15]]


In [110]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print('--------------')
print(lower)

[[0 1 2 3]]
--------------
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [111]:
left, right = np.hsplit(grid, [2]) #这里默认沿着axis=1 也就是列来划分 因为2D数据 所以axis=1对应列 
#[2]说明第三列划分 因为第三列不包含在subarray里面 所以刚好是2列对分 或者简单理解为沿着y轴切
print(left)
print('--------')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
--------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [112]:
left, right = np.hsplit(grid, [3])
print(left)
print('--------')
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
--------
[[ 3]
 [ 7]
 [11]
 [15]]


In [115]:
#同理还有一个3D划分 dsplit
z3d = np.concatenate([z,zadd1], axis=0) #还是按照axis比较靠谱 012对应三个zxy
print(z3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [116]:
up,down = np.dsplit(z3d,[1]) #这里可以理解为沿着z轴切
print(up)
print('-----------')
print(down)

[[[ 1]
  [ 3]]

 [[ 5]
  [ 7]]

 [[ 9]
  [11]]]
-----------
[[[ 2]
  [ 4]]

 [[ 6]
  [ 8]]

 [[10]
  [12]]]


In [117]:
up, low = np.vsplit(z3d, [2]) #沿着xy平面切 z增加
print(up)
print('--------------')
print(low)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------
[[[ 9 10]
  [11 12]]]


In [119]:
up, low = np.hsplit(z3d, [1]) #沿着xz平面切 y增加
print(up)
print('--------------')
print(low)

[[[ 1  2]]

 [[ 5  6]]

 [[ 9 10]]]
--------------
[[[ 3  4]]

 [[ 7  8]]

 [[11 12]]]


In [120]:
up,down = np.dsplit(z3d,[1]) #沿着yz平面切 x增加
print(up)
print('-----------')
print(down)

[[[ 1]
  [ 3]]

 [[ 5]
  [ 7]]

 [[ 9]
  [11]]]
-----------
[[[ 2]
  [ 4]]

 [[ 6]
  [ 8]]

 [[10]
  [12]]]


In [121]:
#向量化操作比循环快很多 这也np数组的优势
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [122]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [123]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [124]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [127]:
"""The following table lists the arithmetic operators implemented in NumPy:
Operator	Equivalent ufunc	Description
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)
"""
np.add(x, 2)

array([2, 3, 4, 5])

In [128]:
np.abs(-(0.5*x + 1) ** 2)

array([1.  , 2.25, 4.  , 6.25])

In [129]:
c = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(c)

array([5., 5., 2., 1.])

In [130]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [131]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [132]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [133]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [134]:
"""
There are also some specialized versions that are useful for maintaining precision with very small input
When x is very small, these functions give more precise values than if the raw np.log or np.exp were to be used.
"""

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [135]:
"""
NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, 
conversions from radians to degrees, rounding and remainders, and much more.
A look through the NumPy documentation reveals a lot of interesting functionality.

Another excellent source for more specialized and obscure ufuncs is the submodule scipy.special. 
If you want to compute some obscure mathematical function on your data, chances are it is implemented in scipy.special. 
There are far too many functions to list them all
but the following snippet shows a couple that might come up in a statistics context:
"""
from scipy import special

In [136]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [137]:
"""
For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored.
Rather than creating a temporary array, this can be used to write computation results directly to the memory location 
where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:
"""

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [138]:
"""
If we had instead written y[::2] = 2 ** x, this would have resulted in the creation of a temporary array to hold the results of 2 ** x, 
followed by a second operation copying those values into the y array. 
This doesn't make much of a difference for such a small computation, 
but for very large arrays the memory savings from careful use of the out argument can be significant.
"""
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [139]:
"""
For binary ufuncs, there are some interesting aggregates聚合函数 that can be computed directly from the object. 
For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. 
A reduce 归约 repeatedly applies a given operation to the elements of an array until only a single result remains.
For example, calling reduce on the add ufunc returns the sum of all elements in the array:

"""
x = np.arange(1, 6)
np.add.reduce(x)

15

In [140]:
np.multiply.reduce(x)

120

In [141]:
"""
If we'd like to store all the intermediate results of the computation, we can instead use accumulate:
"""

np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [142]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [143]:
"""
Finally, any ufunc can compute the output of all pairs of two different inputs using the outer method. 
This allows you, in one line, to do things like create a multiplication table:
"""

x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [144]:
y = np.arange(7, 12)
np.multiply.outer(x, y)

array([[ 7,  8,  9, 10, 11],
       [14, 16, 18, 20, 22],
       [21, 24, 27, 30, 33],
       [28, 32, 36, 40, 44],
       [35, 40, 45, 50, 55]])

In [145]:
"""
Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question. 
Perhaps the most common summary statistics are the mean and standard deviation, 
which allow you to summarize the "typical" values in a dataset, 
but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here.
"""

L = np.random.random(100)
sum(L)

52.12818058833704

In [146]:
np.sum(L)

52.12818058833702

In [149]:
"""
However, because it executes the operation in compiled code, 
NumPy's version of the operation is computed much more quickly:

Be careful, though: the sum function and the np.sum function are not identical, which can sometimes lead to confusion! 
In particular, their optional arguments have different meanings, and np.sum is aware of multiple array dimensions,
as we will see in the following section.

"""

big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array) #much more faster


151 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
693 µs ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [151]:
np.min(big_array), np.max(big_array)

(1.8636745751088313e-06, 0.9999994002429613)

In [152]:
%timeit min(big_array)
%timeit np.min(big_array)

98.1 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
404 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [153]:
"""
Similarly, Python has built-in min and max functions, used to find the minimum value and maximum value of any given array:
NumPy's corresponding functions have similar syntax, and again operate much more quickly:

For min, max, sum, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:
Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!
"""

print(big_array.min(), big_array.max(), big_array.sum())

1.8636745751088313e-06 0.9999994002429613 500778.3285017098


In [154]:
M = np.random.random((3, 4))
print(M)

[[0.32996797 0.26452322 0.309935   0.52952763]
 [0.58032452 0.982702   0.25201423 0.36389056]
 [0.96181939 0.81145838 0.96781133 0.12969939]]


In [155]:
"""
By default, each NumPy aggregation function will return the aggregate over the entire array:
"""

M.sum()

6.483673603352241

In [156]:
"""
Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. 
For example, we can find the minimum value within each column by specifying axis=0:
"""

M.min(axis=0) #按行 就是不同行比较 自然的结果就是得出每列的最小值 或者就是理解为把行消灭=变为一行
#简单理解就是剩下一行 或者每列取最小值

array([0.32996797, 0.26452322, 0.25201423, 0.12969939])

In [157]:
"""
The way the axis is specified here can be confusing to users coming from other languages. 
The axis keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will be returned. 
So specifying axis=0 means that the first axis will be collapsed: for two-dimensional arrays, 
this means that values within each column will be aggregated.

"""
M.min(axis=1)  #剩下一列 或者每行取最小值

array([0.26452322, 0.25201423, 0.12969939])

In [158]:
"""
NumPy provides many other aggregation functions, but we won't discuss them in detail here. 
Additionally, most aggregates have a NaN-safe counterpart that computes the result while ignoring missing values, 
which are marked by the special IEEE floating-point NaN value (for a fuller discussion of missing data, see Handling Missing Data).
Some of these NaN-safe functions were not added until NumPy 1.8, so they will not be available in older NumPy versions.

The following table provides a list of useful aggregation functions available in 

Function Name	NaN-safe Version	Description
np.sum	np.nansum	Compute sum of elements
np.prod	np.nanprod	Compute product of elements
np.mean	np.nanmean	Compute mean of elements
np.std	np.nanstd	Compute standard deviation
np.var	np.nanvar	Compute variance
np.min	np.nanmin	Find minimum value
np.max	np.nanmax	Find maximum value
np.argmin	np.nanargmin	Find index of minimum value
np.argmax	np.nanargmax	Find index of maximum value
np.median	np.nanmedian	Compute median of elements
np.percentile	np.nanpercentile	Compute rank-based statistics of elements
np.any	N/A	Evaluate whether any elements are true
np.all	N/A	Evaluate whether all elements are true
We will see these aggregates often throughout the rest of the book.

"""

"""
As a simple example, let's consider the heights of all US presidents. 
This data is available in the file president_heights.csv, which is a simple comma-separated list of labels and values:
"""
c = np.ones((3, 3))
c * c            # NOT matrix multiplication!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [159]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [160]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [161]:
a > b

array([False, False,  True, False])

In [162]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [163]:
np.logical_and(a, b)

array([ True, False, False, False])

In [164]:
a = np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [166]:
a = np.arange(4)
print(a)
a.reshape(4,1) + np.array([2,3,5])  #broadcasting
#0 0 0 0
#1 1 1 1
#2 2 2 2
#3 3 3 3

[0 1 2 3]


array([[2, 3, 5],
       [3, 4, 6],
       [4, 5, 7],
       [5, 6, 8]])

In [167]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [168]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [169]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a, b)

False

In [170]:
np.array_equal(a, c)

True

In [171]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [172]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [174]:
x.sum(axis=0)   # columns (first dimension) 对2维数据来说 axis=0 就是行坍缩 也可以理解为沿着不同的行压成一行

array([3, 3])

In [175]:
x.sum(axis=1)

array([2, 4])

In [176]:
x[:, 0].sum()

3

In [177]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [178]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [179]:
x = np.random.rand(2, 2, 2)
print(x)

[[[0.21231753 0.09264977]
  [0.61937895 0.48770542]]

 [[0.64088764 0.6058022 ]
  [0.09673807 0.7752722 ]]]


In [183]:
print(x[0,0,0])

0.21231752602438458


In [184]:
print(x[0,0,1])

0.09264976793264179


In [185]:
print(x[0,1,0])

0.619378953114526


In [186]:
print(x[0,1,1])

0.48770542233072156


In [180]:
x.sum(axis=0)#对3D数据来说 012对应zxy axis=0就是直接压缩z到一维

array([[0.85320517, 0.69845197],
       [0.71611702, 1.26297763]])

In [181]:
x.sum(axis=1)#对3D数据来说 012对应zxy 这里有点特别 虽然是压缩x 但是同一个高度(z)的平面的数据进行x坍缩

array([[0.83169648, 0.58035519],
       [0.73762571, 1.3810744 ]])

In [187]:
x.sum(axis=2)#对3D数据来说 012对应zxy 这里2对应y轴 就是每个z平面 坍缩y轴

array([[0.30496729, 1.10708438],
       [1.24668984, 0.87201027]])

In [188]:
x.sum(axis=2)[0, 1] 

1.1070843754452475

In [189]:
x.sum(axis=2)[1, 1] 

0.8720102734983134

In [190]:
x[0, 1, :].sum()  

1.1070843754452475

In [191]:
x[0, 0, :].sum()  

0.3049672939570264

In [192]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [193]:
np.median(x)

1.5

In [194]:
np.median(y, axis=0) # first axis 本质就是沿着行坍缩 也就是每列的中位值 非平均值！！！

array([3., 4., 2.])

In [195]:
np.median(y, axis=1) # last axis 本质就是沿着列坍缩 也就是每行的中位值 非平均值！！！

array([2., 5.])

In [196]:
np.median(y, axis=-1) # last axis 本质就是沿着列坍缩 也就是每行的中位值 非平均值！！！

array([2., 5.])

In [197]:
y[0,:].mean()

2.0

In [198]:
y[1,:].mean()

4.0

In [199]:
x.std()          # full population standard dev. 方差 标准差 公式看了明白其含义

0.82915619758885

In [200]:
x = np.array([1, 3, 2])
x.min()

1

In [201]:
x.max()

3

In [202]:
x.argmin()  # index of minimum value

0

In [203]:
x.argmax()  # index of maximum value

1

In [204]:
np.all([True, True, False]) #满足所有

False

In [205]:
np.any([True, True, False]) #满足任一

True

In [206]:
a = np.zeros((100, 100))
np.any(a != 0)

False

In [207]:
np.all(a == a)

True

In [208]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [209]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [210]:
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [211]:
a = np.ones((4, 5))
a[0] = 2  # we assign an array of dimension 0 to an array of dimension 1
a

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [212]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [213]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

(4, 1)

In [214]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [215]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [216]:
# the numpy.ogrid function allows to directly create vectors x and y of the previous example, with two "significant dimensions":
x, y = np.ogrid[0:5, 0:5]
x, y

(array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]]))

In [217]:
x.shape, y.shape

((5, 1), (1, 5))

In [219]:
distance = np.sqrt(x ** 2 + y ** 2)
print(distance)

[[0.         1.         2.         3.         4.        ]
 [1.         1.41421356 2.23606798 3.16227766 4.12310563]
 [2.         2.23606798 2.82842712 3.60555128 4.47213595]
 [3.         3.16227766 3.60555128 4.24264069 5.        ]
 [4.         4.12310563 4.47213595 5.         5.65685425]]


In [220]:
#So, np.ogrid is very useful as soon as we have to handle computations on a grid. 
#On the other hand, np.mgrid directly provides matrices full of indices for cases 
#where we can't (or don't want to) benefit from broadcasting:
x, y = np.mgrid[0:4, 0:4]
x

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [221]:
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [222]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [223]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [224]:
#Higher dimensions: last dimensions ravel out "first"
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [226]:
a = np.arange(8).reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [227]:
a.ravel() #每个z高度 把y坍缩 ravel是让数据扁平1维化

array([0, 1, 2, 3, 4, 5, 6, 7])

In [228]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [229]:
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [230]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=0)#行坍缩 就是按每列排序
b

array([[1, 2, 1],
       [4, 3, 5]])

In [231]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)#列坍缩 就是按每行排序
b #a不会改变

array([[3, 4, 5],
       [1, 1, 2]])

In [232]:
a.sort(axis=1)
a #原地改变a

array([[3, 4, 5],
       [1, 1, 2]])

In [233]:
a

array([[3, 4, 5],
       [1, 1, 2]])

In [234]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a) #排完序后把原先对应的index输出
j

array([2, 3, 1, 0], dtype=int64)

In [235]:
a[j]

array([1, 2, 3, 4])

In [236]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a) #多维数组也是返回一个数字 而不是多维索引 因为上numpy的内部会将高维数组转化成一维之后再进行这个操作
#我们可以reshape一下数组来进行验证
j_min = np.argmin(a)
j_max, j_min

(0, 2)

In [237]:
a[j_max],a[j_min]

(4, 1)

In [240]:
arr=np.zeros((5,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
(5, 5)
float64


In [241]:
arr.tolist() #将一个ndarray转化成Python原生的list进行返回

[[0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0]]

In [242]:
nums = [1, 3, 4, 6]
arr = np.array(nums)

In [243]:
type(arr)

numpy.ndarray

In [244]:
type(nums)

list

In [245]:
arr = np.array([[1,2,3],[2,2,3]])

In [247]:
arr+arr #等价于 np.add(arr,arr)

array([[2, 4, 6],
       [4, 4, 6]])

In [248]:
arr-arr #等价于 np.subtract(arr,arr)

array([[0, 0, 0],
       [0, 0, 0]])

In [249]:
arr*arr #等价于 np.multiply(arr,arr)

array([[1, 4, 9],
       [4, 4, 9]])

In [250]:
arr/arr #元素一一对应进行相应的四则运算 #等价于 np.divide(arr,arr) 注意不能除0

array([[1., 1., 1.],
       [1., 1., 1.]])

In [251]:
3+arr #要对3进行广播 广播目的是为了于arr的shape匹配 再进行运算 等价于 np.full_like(arr,3)+arr

array([[4, 5, 6],
       [5, 5, 6]])

In [252]:
arr = np.array([[1,2,3],[2,2,3]])

In [253]:
base=np.array([[3],[2]])

In [254]:
base.shape

(2, 1)

In [255]:
arr+base

array([[4, 5, 6],
       [4, 4, 5]])

In [256]:
base2=np.array([[1,3,2]])

In [257]:
base2.shape

(1, 3)

In [258]:
arr*base2

array([[1, 6, 6],
       [2, 6, 6]])

In [259]:
a=np.arange(10)
b=np.arange(10,20)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [260]:
c=np.array([1,0,0,0,1,1,0,0,1,1])
np.where(c,a,b) #c里面是1 取a的值 否则取b的值

array([ 0, 11, 12, 13,  4,  5, 16, 17,  8,  9])

In [261]:
np.where(c,1,b)

array([ 1, 11, 12, 13,  1,  1, 16, 17,  1,  1])

In [262]:
a=np.arange(10)

In [263]:
a.mean()

4.5

In [264]:
a.std()

2.8722813232690143

In [265]:
a.var()

8.25

In [266]:
#median和percentile分别是求中位数与百分位数，它们不是Numpy当中array的函数，而是numpy的库函数
#所以我们需要把array当做参数传入 percentile这个函数还需要额外传入一个int，表示我们想要得到的百分位数，
#比如我们想要知道50%位置上的数，则输入50
np.median(a) #奇数个数就是中间那个 偶数个数是中间左右边的数的平均值
#123 median是2 1234 median是（2+3）/2=2.5

4.5

In [268]:
np.percentile(a,50)

4.5

In [269]:
np.percentile(a,90)

8.1

In [271]:
arr=np.arange(8).reshape(2,2,2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [272]:
#这里返回的索引有点奇怪，和我们想的不同，居然不是一个三维的索引而是一维的
#实际上numpy的内部会将高维数组转化成一维之后再进行这个操作，我们可以reshape一下数组来进行验证
arr.argmax()

7

In [273]:
arr.argmin()

0

In [283]:
arr1d=arr.reshape((1,-1))
print(arr1d)

[[0 1 2 3 4 5 6 7]]


In [284]:
arr1d.shape

(1, 8)

In [287]:
arr1d[0,7]

7

In [288]:
arr1d[0,0]

0

In [285]:
arr2=np.arange(8)
arr2.shape

(8,)

In [286]:
arr2[7]

7

In [289]:
arr=np.arange(8).reshape(4,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [303]:
arr[2,1]=2
print(arr)

[[0 1]
 [2 3]
 [4 2]
 [6 7]]


In [304]:
#沿着行坍缩 就是每个列排序
print(np.sort(arr,axis=0))

[[0 1]
 [2 2]
 [4 3]
 [6 7]]


In [305]:
#沿着列坍缩 就是每个行排序
print(np.sort(arr,axis=1))

[[0 1]
 [2 3]
 [2 4]
 [6 7]]


In [306]:
a = np.array([1, 2, 8, 4, 6])
a.sort()
print(a)


[1 2 4 6 8]


In [307]:
arr=np.array([1,3,4,5,6,1,3])
np.unique(arr)

array([1, 3, 4, 5, 6])

In [309]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [311]:
np.random.shuffle(arr) #in place method 就地生效
print(arr)

[8 5 7 6 0 2 1 4 3 9]


In [312]:
a=np.random.normal(3,2,20)
print(a)

[ 3.02286023  1.50227932  4.44105374 -2.29208034  4.38430418  1.9529474
  7.88096045  0.95192698  0.2924899   2.5797164   4.75260655  1.57907081
  2.65210891  4.50057843  1.69462575  3.57489879  3.25453107  1.22107149
  1.46965978  0.26611215]


In [314]:
#np.random.choice(a, size=None, replace=True, p=None)
#a：一维数组或者int型变量，如果是数组，就按照里面的范围来进行采样，如果是单个变量，就对np.arange(a)进行采样。
#size：int 或 tuple；可选参数；  确定了输出的shape. 如果给定的是(m, n, k), 那么 m * n * k 个采样点将会被采样.
#默认为零，也就是只有一个采样点会被采样回来。
#replace : 布尔参数；可选参数 ；决定采样中是否有重复值
#p :一维数组；可选参数 ；对应着a中每个采样点的概率分布，如果没有标出，则使用标准分布
samples=np.random.choice(20,3)
print(a[samples])

[3.25453107 7.88096045 7.88096045]


In [315]:
samples=np.random.choice(20,3,replace=False)
print(a[samples])

[2.5797164  1.69462575 1.9529474 ]


In [317]:
arr3d=np.arange(8).reshape(2,2,2)
print(arr3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [324]:
arr3d.sum(axis=0) #对3D来说 axis=0是z轴 沿着z轴压缩 叠加值到xy平面 本来是(2,2,2) 少了第一个维度z轴的2
#剩下的xy平面数组是2X2  压缩方向是沿着z轴压缩到原点

array([[ 4,  6],
       [ 8, 10]])

In [325]:
arr3d.sum(axis=1) #对3D来说 axis=1是x轴 沿着x轴压缩 叠加值到zy平面 注意z在前 所以本来是(2,2,2) 少了第二个维度x轴的2
#剩下的zy平面是2X2 压缩方向是沿着x轴压缩到原点

array([[10, 12],
       [ 2,  4]])

In [326]:
arr3d.sum(axis=2) #对3D来说 axis=2是y轴 沿着y轴压缩 叠加值到zx平面 注意z在前 所以本来是(2,2,2) 少了第二个维度y轴的2
#剩下的zx平面是2X2 压缩方向是沿着y轴压缩到原点
#特别注意这里的顺序是9 13和1 5 不是13 9和5 1 需要画个3D示意图理解

array([[ 9, 13],
       [ 1,  5]])

In [327]:
# 将列表转换为 ndarray 
x =  [1,2,3] 
a = np.asarray(x)  
print(a)

[1 2 3]


In [4]:
arr9 = np.full([2,3], fill_value=3)
arr9

array([[3, 3, 3],
       [3, 3, 3]])

In [5]:
data = [[1,2,3], [4,5,6]]
arr10 = np.full_like(data, 8)
arr10

array([[8, 8, 8],
       [8, 8, 8]])

In [6]:
# numpy.identity(n, dtype=None)
arr11 = np.identity(5)
arr11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
"""
numpy.eye(N, M=None, k=0, dtype=<class‘float’>, order=’C’)
N: 行数
M：列数，默认等于N
k：对角线索引：0（默认）为主对角线，正值是指上对角线，负值是指到下对角线
order: {'C', 'F'}输出是否应存储在主要行（C样式）中或内存中的列主（Fortran样式）顺序
"""
arr12 = np.eye(5)
arr12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr12 = np.eye(5,k=1)
arr12

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [9]:
def fun(x, y):
    return x * 10 + y

np.fromfunction(fun, (4, 5), dtype=np.int)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [10]:
def my_dot(a, b):
    return a * b

np.fromfunction(my_dot, (2, 3))

array([[0., 0., 0.],
       [0., 1., 2.]])

In [11]:
np.fromfunction(lambda i,j:i+j,(2, 3))

array([[0., 1., 2.],
       [1., 2., 3.]])

In [12]:
arr3d=np.arange(8).reshape(2,2,2)
print(arr3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
arr3d*2

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [14]:
arr3d*arr3d

array([[[ 0,  1],
        [ 4,  9]],

       [[16, 25],
        [36, 49]]])

In [15]:
arr3d+2

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [16]:
arr3d + arr3d

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [17]:
arr3d - arr3d

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [19]:
arr3d / arr3d #小心除0

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[[nan,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [21]:
# *=、+=运算会修改原对象，而不是创建新对象
arr3d *= 2
arr3d

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [23]:
# shape相同的数组之间比较会生成布尔数组
arr2 = arr3d + 1
arr2 > arr3d

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [25]:
#NumPy中拷贝分为三种情况：
#完全不拷贝:一个数组的任何变化都反映在另一个数组上，包括值变化和形状变化
#浅拷贝:一个数组值会变化会反映在另一个数组上，但是形状不变化
#深拷贝:创建原数组的副本，副本的任何变化都不会反映在原数组上
# 完全不拷贝
a = np.arange(12)
b = a
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b[5] = 500
b

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9,  10,  11])

In [28]:
a

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9,  10,  11])

In [29]:
b is a

True

In [30]:
b.shape = (2, 6)
b

array([[  0,   1,   2,   3,   4, 500],
       [  6,   7,   8,   9,  10,  11]])

In [31]:
a

array([[  0,   1,   2,   3,   4, 500],
       [  6,   7,   8,   9,  10,  11]])

In [32]:
# 浅拷贝
a = np.arange(12)
c = a.view() #视图 浅拷贝
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
c is a

False

In [35]:
c.base is a #shape 意思就是c和a形状是一样的

True

In [36]:
c[2] = 200
c

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [37]:
a

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [38]:
c.shape = (2,6)
c

array([[  0,   1, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [39]:
a

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [40]:
# 深拷贝
a = np.arange(12)
d = a.copy()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
d is a

False

In [43]:
d.base is a #深拷贝 连结构都拷贝副本

False

In [44]:
d[1] = 100
d

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [45]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
d.shape = (2,6)
d

array([[  0, 100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [47]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
#数组切片是原始数组的视图，不是复制品，如果要得到切片的副本，应该使用copy()方法
#在多维数组中索引，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）
#切片的基本语法 ndarray[i : j : k]，其中i为起始下标，j为结束下标（不包括j），k为步长（默认为1）
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[1:9:2]

array([1, 3, 5, 7])

In [50]:
arr[4:-3] #-1是最后一个元素

array([4, 5, 6])

In [51]:
arr[9:4:-2]

array([9, 7, 5])

In [52]:
arr[:] = 1
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
ndarr = np.arange(16).reshape((4, 4))
ndarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
ndarr[:2] # 行，等效于arr2[:2, :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [55]:
ndarr[:2, :2] # 前两行的前两列

array([[0, 1],
       [4, 5]])

In [56]:
ndarr[::2, -2] # 步长为2的行的倒数第二列

array([ 2, 10])

In [57]:
ndarr3 = np.arange(27).reshape((3,3,3))
ndarr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
ndarr3[:2] #z轴，等效于arr2[:2,:,:] #画个3D示意图更好理解

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [60]:
ndarr3[:,0,:] 

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [61]:
ndarr3[:,:,0] #y轴 切3D数据画示意图 其中X轴往正南 Y轴正东 Z轴垂直XY平面或者理解为垂直纸面

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [62]:
ndarr3[:,1:3,1:3] #z轴，等效于arr2[:2,:,:] #画个3D示意图更好理解

array([[[ 4,  5],
        [ 7,  8]],

       [[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]]])

In [63]:
ndarr3[1:3,1:3,1:3] #z轴，等效于arr2[:2,:,:] #画个3D示意图更好理解

array([[[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]]])

In [64]:
arr = np.arange(10)
ndarr = np.arange(16).reshape((4, 4))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
ndarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
ndarr[2, [1, 2]] # 第2行的第1、2列元素

array([ 9, 10])

In [67]:
ndarr[:3, [0,1]] # 前3行的第0、1列元素 #注意冒号不包括右边界 但是中括号包括

array([[0, 1],
       [4, 5],
       [8, 9]])

In [68]:
arr3 = np.arange(36).reshape(6,6) 
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
# 取出第3，2, 5行
arr3[[3, 4, 5]]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [70]:
# 使用负数索引将会从末尾开始选取行
arr3[[-4, -2 , -1]]

array([[12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [71]:
arr3[[1, 2, 3], [1, 2, 3]] # 取出下标为(1, 1), (2, 2), (3, 3)的元素 

array([ 7, 14, 21])

In [72]:
arr3[[1, 2, 3]][:, [1, 2, 3]]  # 同时在行和列上进行花式索引 # 123行的123列数据

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [73]:
arr = np.arange(12)

In [74]:
arr.reshape((4, 3)) # order默认为‘C’ ，按列读取。等效于reshape(4, 3) 不会改变原数组

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
# resize()会修改对象本身
arr.resize((4,3))

In [77]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
ndarr = np.arange(12).reshape(3, 4)
ndarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
ndarr.flatten() # 默认order='C'，按列读取 也就是一行一行读

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
ndarr.flatten(order='F') # 按行读取 也就是一列一列读

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [81]:
ravel_ndarr = ndarr.ravel() # flatten()返回新对象，ravel()返回视图 视图是浅拷贝 改值但不影响shape
ravel_ndarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
ravel_ndarr[1] = 100
ndarr

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [83]:
ravel_ndarr.resize(2,6)
ravel_ndarr

array([[  0, 100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [84]:
ndarr

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [85]:
#concatenate

#沿着一条轴连接一组（多个）数组。除了与axis对应的轴之外，其它轴必须有相同的形状。

#vstack、row_stack

#以追加行的方式对数组进行连接（沿轴0）

#hstack

#以追加列的方式对数组进行连接（沿轴1）

#column_stack

#类似于hstack，但是会先将一维数组转换为二维列向量

#dstack

#以面向“深度”的方式对数组进行叠加

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [86]:
np.concatenate((a, b), axis=0) # 可以查看函数说明 沿着x轴增加 就是增加行数

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
np.concatenate((a, b.T), axis=1) # 可以查看函数说明 沿着y轴增加 就是增加列数 但是b得调整 保证除了axis=N轴以外的其它轴必须有相同的形状

array([[1, 2, 5],
       [3, 4, 6]])

In [88]:
np.concatenate((a, a.T), axis=1)

array([[1, 2, 1, 3],
       [3, 4, 2, 4]])

In [89]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])

In [90]:
np.vstack((a, b)) #水平堆叠 就是增加行数

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [91]:
np.hstack((a, b)) #垂直堆叠 就是增加列数 对于shape一样的两个数组来说 直接就可以用vstack和hstack

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [92]:
np.row_stack((a, b))#等价于vstrack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [93]:
np.column_stack((a, b))#类似于hstack

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [94]:
np.dstack((a, b)) #在z轴上叠加 变成3D数据 可以理解为a把456往z轴堆叠 b把40 50 60往z轴堆叠

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]]])

In [5]:
split_arr = np.arange(36).reshape(6, -1) #-1表示第一维是6情况下 第二维自己计算
split_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
a, b, c = np.split(split_arr, 3, axis=0) # 可以查看函数说明 沿着axis=0 对2D来说就是沿着x轴切

In [7]:
print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
print(c)

[[24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [9]:
a, b, c = np.split(split_arr, 3, axis=1) # 可以查看函数说明
print(a)

[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]]


In [10]:
#hsplit、vsplit、dsplit
#split的便捷化函数，分别沿轴0、轴1、轴2进行拆分
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [11]:
np.repeat(arr, 2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [12]:
# 指定每个元素的重复次数
# 0重复2次，1重复3次，2重复4次，3重复5次
np.repeat(arr, [2, 3, 4, 5])

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [13]:
ndarr = np.arange(6).reshape(2, 3)
ndarr

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
np.repeat(ndarr, 2) # 不指定轴会被扁平化

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [15]:
np.repeat(ndarr, 2, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [16]:
np.repeat(ndarr, 2, axis=1)

array([[0, 0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5, 5]])

In [17]:
ndarr

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
np.tile(ndarr, 2) #针对整个数组 对标量是横向扩展

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [20]:
np.tile(ndarr, (1,2)) #把整个ndarr看出一个元素

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [21]:
np.tile(ndarr, (2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [22]:
arr1 = np.random.randn(10)
arr1

array([-1.53352628, -1.01734457,  0.86023037, -1.04461938, -0.51768177,
        0.27762269,  0.16081488,  1.81737404,  0.55408072, -1.84650788])

In [23]:
np.sort(arr1)

array([-1.84650788, -1.53352628, -1.04461938, -1.01734457, -0.51768177,
        0.16081488,  0.27762269,  0.55408072,  0.86023037,  1.81737404])

In [24]:
arr1

array([-1.53352628, -1.01734457,  0.86023037, -1.04461938, -0.51768177,
        0.27762269,  0.16081488,  1.81737404,  0.55408072, -1.84650788])

In [25]:
arr1.sort() # 就地进行排序，修改原数组
arr1

array([-1.84650788, -1.53352628, -1.04461938, -1.01734457, -0.51768177,
        0.16081488,  0.27762269,  0.55408072,  0.86023037,  1.81737404])

In [26]:
arr2 = np.random.randn(3, 4)
arr2

array([[ 0.05441127,  1.23825163,  0.23837631, -0.24073376],
       [-0.30528427,  1.62417319,  1.2138642 ,  0.24789709],
       [ 0.72151558,  0.76819941,  1.22975989, -0.5536665 ]])

In [27]:
np.sort(arr2, axis=1) # 按列排序

array([[-0.24073376,  0.05441127,  0.23837631,  1.23825163],
       [-0.30528427,  0.24789709,  1.2138642 ,  1.62417319],
       [-0.5536665 ,  0.72151558,  0.76819941,  1.22975989]])

In [28]:
np.sort(arr2, axis=0) # 按行排序

array([[-0.30528427,  0.76819941,  0.23837631, -0.5536665 ],
       [ 0.05441127,  1.23825163,  1.2138642 , -0.24073376],
       [ 0.72151558,  1.62417319,  1.22975989,  0.24789709]])

In [29]:
arr = np.arange(6).reshape(2,3) + 10
arr

array([[10, 11, 12],
       [13, 14, 15]])

In [30]:
np.argmax(arr) # axis默认为None，返回flatten之后的索引

5

In [31]:
np.argmax(arr, axis=0)

array([1, 1, 1], dtype=int64)

In [32]:
np.argmax(arr, axis=1)

array([2, 2], dtype=int64)

In [33]:
np.argmin(arr, axis=1)

array([0, 0], dtype=int64)

In [34]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
np.diag(arr)

array([0, 4, 8])

In [36]:
np.diag(arr, 1)

array([1, 5])

In [37]:
diag_arr = np.array([1, 2, 3])
np.diag(diag_arr)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
# 计算对角线元素的和
np.trace(arr)

12

In [39]:
# 计算矩阵行列式
arr2 = np.array([[1, 2], [3, 4]])
np.linalg.det(arr2)

-2.0000000000000004

In [40]:
# 计算矩阵的逆
np.linalg.inv(arr2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [41]:
np.random.rand(3,4)

array([[0.4631988 , 0.32508502, 0.647415  , 0.77334678],
       [0.70541429, 0.13801064, 0.1680293 , 0.46872191],
       [0.0753222 , 0.99416229, 0.63761781, 0.61623979]])

In [42]:
np.random.randint(5, size=(3, 4))

array([[4, 2, 4, 1],
       [0, 0, 4, 1],
       [3, 3, 2, 3]])

In [43]:
np.random.randn(2, 4) #产生正态分布（平均值为0，标准差为1）的样本值

array([[ 0.00238586, -0.86381482,  0.46415472,  0.76999729],
       [ 0.05233531, -0.66245743,  1.46072476,  0.78122939]])

In [44]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([-0.03984081,  0.06558544,  0.247214  ,  0.0581687 ,  0.07374264,
       -0.14261741,  0.03966684,  0.0307813 , -0.22665293,  0.08287636])

In [45]:
# 生成指定范围的样本值
np.random.uniform(1, 2, 100)

array([1.64077246, 1.88693679, 1.83106091, 1.90294192, 1.55088728,
       1.37356383, 1.73183892, 1.0416252 , 1.38283196, 1.97742424,
       1.01042105, 1.70301027, 1.52645013, 1.90136827, 1.08566153,
       1.45091894, 1.1948394 , 1.10297491, 1.79021999, 1.05305378,
       1.76605832, 1.31032375, 1.62653565, 1.01221573, 1.79483777,
       1.89290399, 1.59247518, 1.01751027, 1.4431447 , 1.70810666,
       1.17609503, 1.87604321, 1.34453338, 1.00414624, 1.82222359,
       1.74501316, 1.13712966, 1.78689253, 1.23154081, 1.6734245 ,
       1.16776557, 1.54260165, 1.24776592, 1.93150173, 1.32952128,
       1.66495951, 1.90559916, 1.24982693, 1.92713267, 1.65004751,
       1.03603267, 1.60234218, 1.03127772, 1.15507632, 1.30474852,
       1.72752354, 1.74869846, 1.96601269, 1.84221184, 1.53856112,
       1.67129151, 1.89881943, 1.68690864, 1.7736788 , 1.24861115,
       1.64961065, 1.76036589, 1.8188618 , 1.10577453, 1.39844692,
       1.66162245, 1.85761693, 1.91483091, 1.43462473, 1.62223

In [46]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
x = np.linalg.solve(a,b) 
print ('求解')
print (x)

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
求解
[[ 5.]
 [ 3.]
 [-2.]]


In [48]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [51]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [52]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [53]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [54]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [56]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.27841486 0.2855219  0.42650715]
  [0.38957504 0.16251679 0.86427874]
  [0.73291941 0.17205305 0.27120112]]

 [[0.54364079 0.92779873 0.13977326]
  [0.8607089  0.68348427 0.1038247 ]
  [0.22670177 0.13939858 0.85420006]]

 [[0.80994937 0.50722495 0.18950342]
  [0.58945647 0.94137759 0.12615292]
  [0.16597666 0.83117805 0.10886298]]]


In [58]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.003449903954687583 0.9938616313461005


In [59]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5330449788682202


In [60]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [61]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [63]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [64]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [65]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [66]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [67]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [68]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.07972202 -0.10871048 -0.60154673  0.26325495  0.55341803]
 [ 1.7246751  -0.86847435  0.45376874 -0.18636181  0.08206333]
 [ 2.06138737  1.17347184 -1.24401389  1.08281331 -1.57514879]
 [ 0.18068897  0.48862383  1.63432854 -0.51969709  0.05439064]
 [-1.16106637 -1.20726995  0.0789542   0.20715762 -1.48698497]]


In [69]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [70]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [72]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 4 7]


In [73]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [74]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [75]:
#Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [76]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1] #not easily readable
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.2410599  1.04638185 0.35084907 0.3626538  0.98712722 0.68111955
 0.69676148 0.99998827 0.94151017 0.93581162]
[0.43603724 0.93148183 0.40105453 1.46998579 0.84181428 1.0821468
 0.27270033 0.27579084 0.91191476 0.31191599]


In [77]:
print(Z)
print(X)
print(Y)

[[0.21850451 0.10181185]
 [0.62431898 0.83972661]
 [0.32300914 0.13696776]
 [0.03649743 0.36081258]
 [0.65753604 0.73625166]
 [0.3197406  0.6014065 ]
 [0.67101414 0.18766083]
 [0.96219886 0.27230479]
 [0.57642352 0.74443088]
 [0.89065622 0.28718443]]
[0.21850451 0.62431898 0.32300914 0.03649743 0.65753604 0.3197406
 0.67101414 0.96219886 0.57642352 0.89065622]
[0.10181185 0.83972661 0.13696776 0.36081258 0.73625166 0.6014065
 0.18766083 0.27230479 0.74443088 0.28718443]


In [78]:
#Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.42423568 0.44883746 0.82293093 0.48521057 0.         0.13723311
 0.08247822 0.07829157 0.08115365 0.07955789]


In [79]:
#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [81]:
#How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(v)
print(Z[index])

34.083421309346306
34


In [82]:
#Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.83074831 0.48246053 0.45039173 0.2343502  0.67409409
  0.2803037  0.2612437  0.49216175 0.57647428]
 [0.83074831 0.         0.45218294 0.69485957 0.71774564 0.15734819
  0.59731691 0.57755113 0.56979416 0.35354158]
 [0.48246053 0.45218294 0.         0.24678382 0.29508324 0.33167787
  0.20238034 0.32066876 0.13319503 0.4291124 ]
 [0.45039173 0.69485957 0.24678382 0.         0.21668852 0.5783749
  0.24593102 0.43038778 0.12798948 0.64822705]
 [0.2343502  0.71774564 0.29508324 0.21668852 0.         0.57257138
  0.12412641 0.26959063 0.26711773 0.56029519]
 [0.67409409 0.15734819 0.33167787 0.5783749  0.57257138 0.
  0.44974136 0.42021041 0.46083943 0.2308137 ]
 [0.2803037  0.59731691 0.20238034 0.24593102 0.12412641 0.44974136
  0.         0.184532   0.23086501 0.44240941]
 [0.2612437  0.57755113 0.32066876 0.43038778 0.26959063 0.42021041
  0.184532   0.         0.3984053  0.32056764]
 [0.49216175 0.56979416 0.13319503 0.12798948 0.26711773 0.46083943
  0.23086501 0.398405